### PR TITLE
Optimize debug logs

### PR DESCRIPTION
**Pull request by alovak**
# Changes
* add entry details to the log context
* output matching results in a single entry

# Why Are Changes Being Made

* Due to massive number of log entries and lack of information about entry details it was hard to understand which rule matched.

Now log entry looks like this:
```shell
platform-dev-ach-test-harness-1  | ts=2024-02-02T20:26:29Z msg="starting EntryDetail matching" app=ach-test-harness entry_trace_number=291471029446126 level=info version=v0.
9.1
platform-dev-ach-test-harness-1  | ts=2024-02-02T20:26:29Z msg="FINAL matching score negative=0 positive=4 (DFIAccountNumber, RDFIIdentification, Amount, TransactionCode)" a
pp=ach-test-harness copy_path=/reconciliation/ ed.account_number=55555 ed.amount=10000 ed.entry_type=22 ed.individual_name="Moov Financial        " ed.routing_number=2739701
16 ed.trace_number=291471029446126 entry_trace_number=291471029446126 level=info matcher.account_number=55555 matcher.amount=10000 matcher.entry_type=credit matcher.individual_name= matcher.response_idx=11 matcher.routing_number=273970116 matcher.trace_number= version=v0.9.1
```

before it was:

```
platform-dev-ach-test-harness-1  | ts=2024-02-02T19:50:15Z msg="starting EntryDetail matching" app=ach-test-harness entry_trace_number=291471029029390 level=info version=v0.
9.1
platform-dev-ach-test-harness-1  | ts=2024-02-02T19:50:15Z msg="RDFIIdentification negative match" account_number= amount=551 app=ach-test-harness ed.account_number=55555 ed
.amount=10000 ed.entry_type=22 ed.routing_number=273970116 entry_trace_number=291471029029390 entry_type=credit individual_name= level=info matcher_trace_number= response_id
x=5 return_code=R02 routing_number=221475786 version=v0.9.1
platform-dev-ach-test-harness-1  | ts=2024-02-02T19:50:15Z msg="Amount negative match" account_number= amount=551 app=ach-test-harness ed.account_number=55555 ed.amount=1000
0 ed.entry_type=22 ed.routing_number=273970116 entry_trace_number=291471029029390 entry_type=credit individual_name= level=info matcher_trace_number= response_idx=5 return_c
ode=R02 routing_number=221475786 version=v0.9.1
platform-dev-ach-test-harness-1  | ts=2024-02-02T19:50:15Z msg="TransactionCode type positive match" account_number= amount=551 app=ach-test-harness ed.account_number=55555
ed.amount=10000 ed.entry_type=22 ed.routing_number=273970116 entry_trace_number=291471029029390 entry_type=credit individual_name= level=info matcher_trace_number= response_
idx=5 return_code=R02 routing_number=221475786 version=v0.9.1
platform-dev-ach-test-harness-1  | ts=2024-02-02T19:50:15Z msg="FINAL matching score negative=2 positive=1" account_number= amount=551 app=ach-test-harness ed.account_number
=55555 ed.amount=10000 ed.entry_type=22 ed.routing_number=273970116 entry_trace_number=291471029029390 entry_type=credit individual_name= level=info matcher_trace_number= re
sponse_idx=5 return_code=R02 routing_number=221475786 version=v0.9.1
```

### CODE REVIEW

**Comment by alovak** [comment]
@adamdecaf I can update the context of the `Match` type log fields and remove empty values. I didn't do it because I'm not sure if it's intended to keep only `Amount` in the context:

```go
func (m Match) Context() map[string]log.Valuer {
	logFields := log.Fields{}

	if m.Amount != nil {
		var amount = m.Amount.Value
		logFields["matcher.amount"] = log.Int(amount)
	}

	return logFields
}
```

**Comment by adamdecaf** [comment]
@alovak Want me to merge and release this?

**Comment by alovak** [comment]
@adamdecaf sorry, was on vacation 🌴

**Comment by adamdecaf** [comment]
No worries! Hope you enjoyed the time off!

**Pull request merged**
